version: '3.7'

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app.ts:/myfolder/app.ts
      - ./app.js:/myfolder/app.js
      - ./controllers:/myfolder/controllers
      - ./routes:/myfolder/routes
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  # 컴퓨터이름
  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'nodeBird'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306